[package]
name = "streamfind-rust-mass-spec"
version.workspace = true
edition = "2021"
autotests = false

[dependencies]
streamfind-rust-core = { path = "../core" }
streamfind-rust-external = { path = "../external" }
serde_json = "1"
base64 = "0.22"
cfb = "0.14"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
quick-xml = "0.38"
regex = "1"
zstd = "0.13"

[target.'cfg(windows)'.dependencies]
duckdb = { version = "1.10505.0" }

[target.'cfg(not(windows))'.dependencies]
duckdb = { version = "1.10505.0", features = ["bundled"] }

[dev-dependencies]
streamfind-rust-test-support = { path = "../test-support" }

[[test]]
name = "mass_spec_interface_smoke"
path = "tests/mass_spec_interface_smoke.rs"


[[test]]
name = "nta_interface_smoke"
path = "tests/nta_interface_smoke.rs"
