[package]
name = "streamfind-rust-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
streamfind-rust-core = { path = "../core" }
streamfind-rust-mass-spec = { path = "../mass-spec" }
streamfind-rust-raman = { path = "../raman" }
streamfind-rust-sensors = { path = "../sensors" }

[dev-dependencies]
streamfind-rust-test-support = { path = "../test-support" }
