[package]
name = "streamfind-rust-core"
version.workspace = true
edition = "2021"

[lib]
name = "streamfind_rust_core"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
streamfind-rust-external = { path = "../external" }

[target.'cfg(windows)'.dependencies]
duckdb = { version = "1.10505.0" }

[target.'cfg(not(windows))'.dependencies]
duckdb = { version = "1.10505.0", features = ["bundled", "json"] }

[dev-dependencies]
streamfind-rust-test-support = { path = "../test-support" }
