// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_json_read_file
std::string rcpp_json_read_file(std::string file_path);
RcppExport SEXP _StreamFind_rcpp_json_read_file(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_json_read_file(file_path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_read_subtree
std::string rcpp_json_read_subtree(std::string file_path, std::string path);
RcppExport SEXP _StreamFind_rcpp_json_read_subtree(SEXP file_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_json_read_subtree(file_path, path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_list_children
Rcpp::CharacterVector rcpp_json_list_children(std::string file_path, std::string path);
RcppExport SEXP _StreamFind_rcpp_json_list_children(SEXP file_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_json_list_children(file_path, path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_read_file
std::string rcpp_asm_read_file(std::string file_path);
RcppExport SEXP _StreamFind_rcpp_asm_read_file(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_read_file(file_path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_index_table
Rcpp::DataFrame rcpp_asm_index_table(std::string file_path);
RcppExport SEXP _StreamFind_rcpp_asm_index_table(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_index_table(file_path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_read_subtree
std::string rcpp_asm_read_subtree(std::string file_path, std::string path);
RcppExport SEXP _StreamFind_rcpp_asm_read_subtree(SEXP file_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_read_subtree(file_path, path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_read_primary_data
std::string rcpp_asm_read_primary_data(std::string file_path);
RcppExport SEXP _StreamFind_rcpp_asm_read_primary_data(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_read_primary_data(file_path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_list_children
Rcpp::CharacterVector rcpp_asm_list_children(std::string file_path, std::string path);
RcppExport SEXP _StreamFind_rcpp_asm_list_children(SEXP file_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_list_children(file_path, path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_asm_validate_file
bool rcpp_asm_validate_file(std::string json_file_path, std::string schema_file, std::string schema_root_dir);
RcppExport SEXP _StreamFind_rcpp_asm_validate_file(SEXP json_file_pathSEXP, SEXP schema_fileSEXP, SEXP schema_root_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type json_file_path(json_file_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type schema_file(schema_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type schema_root_dir(schema_root_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_asm_validate_file(json_file_path, schema_file, schema_root_dir));
    return rcpp_result_gen;
END_RCPP
}
// duckdb_list_tables
CharacterVector duckdb_list_tables(std::string db_path);
RcppExport SEXP _StreamFind_duckdb_list_tables(SEXP db_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type db_path(db_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(duckdb_list_tables(db_path));
    return rcpp_result_gen;
END_RCPP
}
// duckdb_json_extension_info
List duckdb_json_extension_info(std::string db_path);
RcppExport SEXP _StreamFind_duckdb_json_extension_info(SEXP db_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type db_path(db_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(duckdb_json_extension_info(db_path));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_schema_validation_ok
bool rcpp_json_schema_validation_ok();
RcppExport SEXP _StreamFind_rcpp_json_schema_validation_ok() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_json_schema_validation_ok());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_schema_validation_error
std::string rcpp_json_schema_validation_error();
RcppExport SEXP _StreamFind_rcpp_json_schema_validation_error() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_json_schema_validation_error());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_make_example
std::string rcpp_json_make_example();
RcppExport SEXP _StreamFind_rcpp_json_make_example() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_json_make_example());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_json_parse
Rcpp::List rcpp_json_parse(const std::string& s);
RcppExport SEXP _StreamFind_rcpp_json_parse(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_json_parse(s));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_new
SEXP rcpp_project_non_target_analysis_new(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_new(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_new(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_get_features
Rcpp::List rcpp_project_non_target_analysis_get_features(SEXP nts_xptr, SEXP analyses, SEXP features, SEXP groups, SEXP components, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, double ppm, double sec, double millisec, bool include_filtered);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_get_features(SEXP nts_xptrSEXP, SEXP analysesSEXP, SEXP featuresSEXP, SEXP groupsSEXP, SEXP componentsSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP, SEXP include_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    Rcpp::traits::input_parameter< bool >::type include_filtered(include_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_get_features(nts_xptr, analyses, features, groups, components, mass, mz, rt, mobility, ppm, sec, millisec, include_filtered));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_get_features_count
Rcpp::List rcpp_project_non_target_analysis_get_features_count(SEXP nts_xptr, CharacterVector analyses, bool include_filtered);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_get_features_count(SEXP nts_xptrSEXP, SEXP analysesSEXP, SEXP include_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< bool >::type include_filtered(include_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_get_features_count(nts_xptr, analyses, include_filtered));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_get_suspects
Rcpp::List rcpp_project_non_target_analysis_get_suspects(SEXP nts_xptr, SEXP analyses, SEXP features, SEXP groups, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, double ppm, double sec, double millisec);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_get_suspects(SEXP nts_xptrSEXP, SEXP analysesSEXP, SEXP featuresSEXP, SEXP groupsSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_get_suspects(nts_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_get_internal_standards
Rcpp::List rcpp_project_non_target_analysis_get_internal_standards(SEXP nts_xptr, SEXP analyses, SEXP features, SEXP groups, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, double ppm, double sec, double millisec);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_get_internal_standards(SEXP nts_xptrSEXP, SEXP analysesSEXP, SEXP featuresSEXP, SEXP groupsSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_get_internal_standards(nts_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_get_transformation_products
Rcpp::List rcpp_project_non_target_analysis_get_transformation_products(SEXP nts_xptr);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_get_transformation_products(SEXP nts_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_get_transformation_products(nts_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_non_target_analysis_assign_transformation_products
bool rcpp_project_non_target_analysis_assign_transformation_products(SEXP nts_xptr, Rcpp::List transformation_products, std::string chromatographic_phase, double mzrMS2);
RcppExport SEXP _StreamFind_rcpp_project_non_target_analysis_assign_transformation_products(SEXP nts_xptrSEXP, SEXP transformation_productsSEXP, SEXP chromatographic_phaseSEXP, SEXP mzrMS2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transformation_products(transformation_productsSEXP);
    Rcpp::traits::input_parameter< std::string >::type chromatographic_phase(chromatographic_phaseSEXP);
    Rcpp::traits::input_parameter< double >::type mzrMS2(mzrMS2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_non_target_analysis_assign_transformation_products(nts_xptr, transformation_products, chromatographic_phase, mzrMS2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_find_features
bool rcpp_nts_find_features(SEXP nts_xptr, std::vector<float> rtWindowsMin, std::vector<float> rtWindowsMax, float ppmThreshold, float noiseThreshold, float minSNR, int minTraces, float baselineWindow, float maxWidth, float baseQuantile, std::string debugAnalysis, float debugMZ, int debugSpecIdx);
RcppExport SEXP _StreamFind_rcpp_nts_find_features(SEXP nts_xptrSEXP, SEXP rtWindowsMinSEXP, SEXP rtWindowsMaxSEXP, SEXP ppmThresholdSEXP, SEXP noiseThresholdSEXP, SEXP minSNRSEXP, SEXP minTracesSEXP, SEXP baselineWindowSEXP, SEXP maxWidthSEXP, SEXP baseQuantileSEXP, SEXP debugAnalysisSEXP, SEXP debugMZSEXP, SEXP debugSpecIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< std::vector<float> >::type rtWindowsMin(rtWindowsMinSEXP);
    Rcpp::traits::input_parameter< std::vector<float> >::type rtWindowsMax(rtWindowsMaxSEXP);
    Rcpp::traits::input_parameter< float >::type ppmThreshold(ppmThresholdSEXP);
    Rcpp::traits::input_parameter< float >::type noiseThreshold(noiseThresholdSEXP);
    Rcpp::traits::input_parameter< float >::type minSNR(minSNRSEXP);
    Rcpp::traits::input_parameter< int >::type minTraces(minTracesSEXP);
    Rcpp::traits::input_parameter< float >::type baselineWindow(baselineWindowSEXP);
    Rcpp::traits::input_parameter< float >::type maxWidth(maxWidthSEXP);
    Rcpp::traits::input_parameter< float >::type baseQuantile(baseQuantileSEXP);
    Rcpp::traits::input_parameter< std::string >::type debugAnalysis(debugAnalysisSEXP);
    Rcpp::traits::input_parameter< float >::type debugMZ(debugMZSEXP);
    Rcpp::traits::input_parameter< int >::type debugSpecIdx(debugSpecIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_find_features(nts_xptr, rtWindowsMin, rtWindowsMax, ppmThreshold, noiseThreshold, minSNR, minTraces, baselineWindow, maxWidth, baseQuantile, debugAnalysis, debugMZ, debugSpecIdx));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_load_features_ms1
bool rcpp_nts_load_features_ms1(SEXP nts_xptr, bool filtered, std::vector<float> rtWindow, std::vector<float> mzWindow, float minTracesIntensity, float mzClust, float presence);
RcppExport SEXP _StreamFind_rcpp_nts_load_features_ms1(SEXP nts_xptrSEXP, SEXP filteredSEXP, SEXP rtWindowSEXP, SEXP mzWindowSEXP, SEXP minTracesIntensitySEXP, SEXP mzClustSEXP, SEXP presenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< bool >::type filtered(filteredSEXP);
    Rcpp::traits::input_parameter< std::vector<float> >::type rtWindow(rtWindowSEXP);
    Rcpp::traits::input_parameter< std::vector<float> >::type mzWindow(mzWindowSEXP);
    Rcpp::traits::input_parameter< float >::type minTracesIntensity(minTracesIntensitySEXP);
    Rcpp::traits::input_parameter< float >::type mzClust(mzClustSEXP);
    Rcpp::traits::input_parameter< float >::type presence(presenceSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_load_features_ms1(nts_xptr, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_load_features_ms2
bool rcpp_nts_load_features_ms2(SEXP nts_xptr, bool filtered, float minTracesIntensity, float isolationWindow, float mzClust, float presence);
RcppExport SEXP _StreamFind_rcpp_nts_load_features_ms2(SEXP nts_xptrSEXP, SEXP filteredSEXP, SEXP minTracesIntensitySEXP, SEXP isolationWindowSEXP, SEXP mzClustSEXP, SEXP presenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< bool >::type filtered(filteredSEXP);
    Rcpp::traits::input_parameter< float >::type minTracesIntensity(minTracesIntensitySEXP);
    Rcpp::traits::input_parameter< float >::type isolationWindow(isolationWindowSEXP);
    Rcpp::traits::input_parameter< float >::type mzClust(mzClustSEXP);
    Rcpp::traits::input_parameter< float >::type presence(presenceSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_load_features_ms2(nts_xptr, filtered, minTracesIntensity, isolationWindow, mzClust, presence));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_create_components
bool rcpp_nts_create_components(SEXP nts_xptr, std::vector<float> rtWindow, float minCorrelation, float debugRT, std::string debugAnalysis);
RcppExport SEXP _StreamFind_rcpp_nts_create_components(SEXP nts_xptrSEXP, SEXP rtWindowSEXP, SEXP minCorrelationSEXP, SEXP debugRTSEXP, SEXP debugAnalysisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< std::vector<float> >::type rtWindow(rtWindowSEXP);
    Rcpp::traits::input_parameter< float >::type minCorrelation(minCorrelationSEXP);
    Rcpp::traits::input_parameter< float >::type debugRT(debugRTSEXP);
    Rcpp::traits::input_parameter< std::string >::type debugAnalysis(debugAnalysisSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_create_components(nts_xptr, rtWindow, minCorrelation, debugRT, debugAnalysis));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_annotate_components
bool rcpp_nts_annotate_components(SEXP nts_xptr, int maxIsotopes, int maxCharge, int maxGaps, float ppm, std::string debugComponent, std::string debugAnalysis);
RcppExport SEXP _StreamFind_rcpp_nts_annotate_components(SEXP nts_xptrSEXP, SEXP maxIsotopesSEXP, SEXP maxChargeSEXP, SEXP maxGapsSEXP, SEXP ppmSEXP, SEXP debugComponentSEXP, SEXP debugAnalysisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type maxIsotopes(maxIsotopesSEXP);
    Rcpp::traits::input_parameter< int >::type maxCharge(maxChargeSEXP);
    Rcpp::traits::input_parameter< int >::type maxGaps(maxGapsSEXP);
    Rcpp::traits::input_parameter< float >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< std::string >::type debugComponent(debugComponentSEXP);
    Rcpp::traits::input_parameter< std::string >::type debugAnalysis(debugAnalysisSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_annotate_components(nts_xptr, maxIsotopes, maxCharge, maxGaps, ppm, debugComponent, debugAnalysis));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_group_features
bool rcpp_nts_group_features(SEXP nts_xptr, std::string method, float rtDeviation, float ppm, int minSamples, float binSize, bool debug, float debugRT);
RcppExport SEXP _StreamFind_rcpp_nts_group_features(SEXP nts_xptrSEXP, SEXP methodSEXP, SEXP rtDeviationSEXP, SEXP ppmSEXP, SEXP minSamplesSEXP, SEXP binSizeSEXP, SEXP debugSEXP, SEXP debugRTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< float >::type rtDeviation(rtDeviationSEXP);
    Rcpp::traits::input_parameter< float >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< int >::type minSamples(minSamplesSEXP);
    Rcpp::traits::input_parameter< float >::type binSize(binSizeSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< float >::type debugRT(debugRTSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_group_features(nts_xptr, method, rtDeviation, ppm, minSamples, binSize, debug, debugRT));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_fill_features
bool rcpp_nts_fill_features(SEXP nts_xptr, bool withinReplicate, bool filtered, float rtExpand, float mzExpand, float maxPeakWidth, float minTracesIntensity, int minNumberTraces, float minIntensity, float rtApexDeviation, float minSignalToNoiseRatio, float minGaussianFit, std::string debugFG);
RcppExport SEXP _StreamFind_rcpp_nts_fill_features(SEXP nts_xptrSEXP, SEXP withinReplicateSEXP, SEXP filteredSEXP, SEXP rtExpandSEXP, SEXP mzExpandSEXP, SEXP maxPeakWidthSEXP, SEXP minTracesIntensitySEXP, SEXP minNumberTracesSEXP, SEXP minIntensitySEXP, SEXP rtApexDeviationSEXP, SEXP minSignalToNoiseRatioSEXP, SEXP minGaussianFitSEXP, SEXP debugFGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< bool >::type withinReplicate(withinReplicateSEXP);
    Rcpp::traits::input_parameter< bool >::type filtered(filteredSEXP);
    Rcpp::traits::input_parameter< float >::type rtExpand(rtExpandSEXP);
    Rcpp::traits::input_parameter< float >::type mzExpand(mzExpandSEXP);
    Rcpp::traits::input_parameter< float >::type maxPeakWidth(maxPeakWidthSEXP);
    Rcpp::traits::input_parameter< float >::type minTracesIntensity(minTracesIntensitySEXP);
    Rcpp::traits::input_parameter< int >::type minNumberTraces(minNumberTracesSEXP);
    Rcpp::traits::input_parameter< float >::type minIntensity(minIntensitySEXP);
    Rcpp::traits::input_parameter< float >::type rtApexDeviation(rtApexDeviationSEXP);
    Rcpp::traits::input_parameter< float >::type minSignalToNoiseRatio(minSignalToNoiseRatioSEXP);
    Rcpp::traits::input_parameter< float >::type minGaussianFit(minGaussianFitSEXP);
    Rcpp::traits::input_parameter< std::string >::type debugFG(debugFGSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_fill_features(nts_xptr, withinReplicate, filtered, rtExpand, mzExpand, maxPeakWidth, minTracesIntensity, minNumberTraces, minIntensity, rtApexDeviation, minSignalToNoiseRatio, minGaussianFit, debugFG));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_blank_subtraction
bool rcpp_nts_blank_subtraction(SEXP nts_xptr, float blankThreshold, float rtExpand, float mzExpand);
RcppExport SEXP _StreamFind_rcpp_nts_blank_subtraction(SEXP nts_xptrSEXP, SEXP blankThresholdSEXP, SEXP rtExpandSEXP, SEXP mzExpandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< float >::type blankThreshold(blankThresholdSEXP);
    Rcpp::traits::input_parameter< float >::type rtExpand(rtExpandSEXP);
    Rcpp::traits::input_parameter< float >::type mzExpand(mzExpandSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_blank_subtraction(nts_xptr, blankThreshold, rtExpand, mzExpand));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_filter_features
bool rcpp_nts_filter_features(SEXP nts_xptr, double minSN, double minIntensity, double minArea, double minWidth, double maxWidth, double maxPPM, double minFwhmRT, double maxFwhmRT, double minFwhmMZ, double maxFwhmMZ, double minGaussianA, double minGaussianMu, double maxGaussianMu, double minGaussianSigma, double maxGaussianSigma, double minGaussianR2, double maxJaggedness, double minSharpness, double minAsymmetry, double maxAsymmetry, int maxModality, double minPlates, Rcpp::LogicalVector onlyFilled, bool removeFilled, int minSizeEIC, int minSizeMS1, int minSizeMS2, double minRelPresenceReplicate, bool removeIsotopes, bool removeAdducts, bool removeLosses);
RcppExport SEXP _StreamFind_rcpp_nts_filter_features(SEXP nts_xptrSEXP, SEXP minSNSEXP, SEXP minIntensitySEXP, SEXP minAreaSEXP, SEXP minWidthSEXP, SEXP maxWidthSEXP, SEXP maxPPMSEXP, SEXP minFwhmRTSEXP, SEXP maxFwhmRTSEXP, SEXP minFwhmMZSEXP, SEXP maxFwhmMZSEXP, SEXP minGaussianASEXP, SEXP minGaussianMuSEXP, SEXP maxGaussianMuSEXP, SEXP minGaussianSigmaSEXP, SEXP maxGaussianSigmaSEXP, SEXP minGaussianR2SEXP, SEXP maxJaggednessSEXP, SEXP minSharpnessSEXP, SEXP minAsymmetrySEXP, SEXP maxAsymmetrySEXP, SEXP maxModalitySEXP, SEXP minPlatesSEXP, SEXP onlyFilledSEXP, SEXP removeFilledSEXP, SEXP minSizeEICSEXP, SEXP minSizeMS1SEXP, SEXP minSizeMS2SEXP, SEXP minRelPresenceReplicateSEXP, SEXP removeIsotopesSEXP, SEXP removeAdductsSEXP, SEXP removeLossesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< double >::type minSN(minSNSEXP);
    Rcpp::traits::input_parameter< double >::type minIntensity(minIntensitySEXP);
    Rcpp::traits::input_parameter< double >::type minArea(minAreaSEXP);
    Rcpp::traits::input_parameter< double >::type minWidth(minWidthSEXP);
    Rcpp::traits::input_parameter< double >::type maxWidth(maxWidthSEXP);
    Rcpp::traits::input_parameter< double >::type maxPPM(maxPPMSEXP);
    Rcpp::traits::input_parameter< double >::type minFwhmRT(minFwhmRTSEXP);
    Rcpp::traits::input_parameter< double >::type maxFwhmRT(maxFwhmRTSEXP);
    Rcpp::traits::input_parameter< double >::type minFwhmMZ(minFwhmMZSEXP);
    Rcpp::traits::input_parameter< double >::type maxFwhmMZ(maxFwhmMZSEXP);
    Rcpp::traits::input_parameter< double >::type minGaussianA(minGaussianASEXP);
    Rcpp::traits::input_parameter< double >::type minGaussianMu(minGaussianMuSEXP);
    Rcpp::traits::input_parameter< double >::type maxGaussianMu(maxGaussianMuSEXP);
    Rcpp::traits::input_parameter< double >::type minGaussianSigma(minGaussianSigmaSEXP);
    Rcpp::traits::input_parameter< double >::type maxGaussianSigma(maxGaussianSigmaSEXP);
    Rcpp::traits::input_parameter< double >::type minGaussianR2(minGaussianR2SEXP);
    Rcpp::traits::input_parameter< double >::type maxJaggedness(maxJaggednessSEXP);
    Rcpp::traits::input_parameter< double >::type minSharpness(minSharpnessSEXP);
    Rcpp::traits::input_parameter< double >::type minAsymmetry(minAsymmetrySEXP);
    Rcpp::traits::input_parameter< double >::type maxAsymmetry(maxAsymmetrySEXP);
    Rcpp::traits::input_parameter< int >::type maxModality(maxModalitySEXP);
    Rcpp::traits::input_parameter< double >::type minPlates(minPlatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type onlyFilled(onlyFilledSEXP);
    Rcpp::traits::input_parameter< bool >::type removeFilled(removeFilledSEXP);
    Rcpp::traits::input_parameter< int >::type minSizeEIC(minSizeEICSEXP);
    Rcpp::traits::input_parameter< int >::type minSizeMS1(minSizeMS1SEXP);
    Rcpp::traits::input_parameter< int >::type minSizeMS2(minSizeMS2SEXP);
    Rcpp::traits::input_parameter< double >::type minRelPresenceReplicate(minRelPresenceReplicateSEXP);
    Rcpp::traits::input_parameter< bool >::type removeIsotopes(removeIsotopesSEXP);
    Rcpp::traits::input_parameter< bool >::type removeAdducts(removeAdductsSEXP);
    Rcpp::traits::input_parameter< bool >::type removeLosses(removeLossesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_filter_features(nts_xptr, minSN, minIntensity, minArea, minWidth, maxWidth, maxPPM, minFwhmRT, maxFwhmRT, minFwhmMZ, maxFwhmMZ, minGaussianA, minGaussianMu, maxGaussianMu, minGaussianSigma, maxGaussianSigma, minGaussianR2, maxJaggedness, minSharpness, minAsymmetry, maxAsymmetry, maxModality, minPlates, onlyFilled, removeFilled, minSizeEIC, minSizeMS1, minSizeMS2, minRelPresenceReplicate, removeIsotopes, removeAdducts, removeLosses));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_filter_suspects
bool rcpp_nts_filter_suspects(SEXP nts_xptr, Rcpp::CharacterVector names, double minScore, double maxErrorRT, double maxErrorMass, Rcpp::IntegerVector idLevels, int minSharedFragments, double minCosineSimilarity);
RcppExport SEXP _StreamFind_rcpp_nts_filter_suspects(SEXP nts_xptrSEXP, SEXP namesSEXP, SEXP minScoreSEXP, SEXP maxErrorRTSEXP, SEXP maxErrorMassSEXP, SEXP idLevelsSEXP, SEXP minSharedFragmentsSEXP, SEXP minCosineSimilaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< double >::type minScore(minScoreSEXP);
    Rcpp::traits::input_parameter< double >::type maxErrorRT(maxErrorRTSEXP);
    Rcpp::traits::input_parameter< double >::type maxErrorMass(maxErrorMassSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type idLevels(idLevelsSEXP);
    Rcpp::traits::input_parameter< int >::type minSharedFragments(minSharedFragmentsSEXP);
    Rcpp::traits::input_parameter< double >::type minCosineSimilarity(minCosineSimilaritySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_filter_suspects(nts_xptr, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_filter_internal_standards
bool rcpp_nts_filter_internal_standards(SEXP nts_xptr, Rcpp::CharacterVector names, double minScore, double maxErrorRT, double maxErrorMass, Rcpp::IntegerVector idLevels, int minSharedFragments, double minCosineSimilarity);
RcppExport SEXP _StreamFind_rcpp_nts_filter_internal_standards(SEXP nts_xptrSEXP, SEXP namesSEXP, SEXP minScoreSEXP, SEXP maxErrorRTSEXP, SEXP maxErrorMassSEXP, SEXP idLevelsSEXP, SEXP minSharedFragmentsSEXP, SEXP minCosineSimilaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< double >::type minScore(minScoreSEXP);
    Rcpp::traits::input_parameter< double >::type maxErrorRT(maxErrorRTSEXP);
    Rcpp::traits::input_parameter< double >::type maxErrorMass(maxErrorMassSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type idLevels(idLevelsSEXP);
    Rcpp::traits::input_parameter< int >::type minSharedFragments(minSharedFragmentsSEXP);
    Rcpp::traits::input_parameter< double >::type minCosineSimilarity(minCosineSimilaritySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_filter_internal_standards(nts_xptr, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_suspect_screening
bool rcpp_nts_suspect_screening(SEXP nts_xptr, Rcpp::List suspects, Rcpp::CharacterVector analyses, double ppm, double sec, double ppmMS2, double mzrMS2, double minCosineSimilarity, int minSharedFragments, bool filtered);
RcppExport SEXP _StreamFind_rcpp_nts_suspect_screening(SEXP nts_xptrSEXP, SEXP suspectsSEXP, SEXP analysesSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP ppmMS2SEXP, SEXP mzrMS2SEXP, SEXP minCosineSimilaritySEXP, SEXP minSharedFragmentsSEXP, SEXP filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type suspects(suspectsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type ppmMS2(ppmMS2SEXP);
    Rcpp::traits::input_parameter< double >::type mzrMS2(mzrMS2SEXP);
    Rcpp::traits::input_parameter< double >::type minCosineSimilarity(minCosineSimilaritySEXP);
    Rcpp::traits::input_parameter< int >::type minSharedFragments(minSharedFragmentsSEXP);
    Rcpp::traits::input_parameter< bool >::type filtered(filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_suspect_screening(nts_xptr, suspects, analyses, ppm, sec, ppmMS2, mzrMS2, minCosineSimilarity, minSharedFragments, filtered));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_filter_features_ms2
bool rcpp_nts_filter_features_ms2(SEXP nts_xptr, int top, double minIntensity, double relMinIntensity, bool blankClean, double mzClust, double blankPresenceThreshold, double globalPresenceThreshold);
RcppExport SEXP _StreamFind_rcpp_nts_filter_features_ms2(SEXP nts_xptrSEXP, SEXP topSEXP, SEXP minIntensitySEXP, SEXP relMinIntensitySEXP, SEXP blankCleanSEXP, SEXP mzClustSEXP, SEXP blankPresenceThresholdSEXP, SEXP globalPresenceThresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type minIntensity(minIntensitySEXP);
    Rcpp::traits::input_parameter< double >::type relMinIntensity(relMinIntensitySEXP);
    Rcpp::traits::input_parameter< bool >::type blankClean(blankCleanSEXP);
    Rcpp::traits::input_parameter< double >::type mzClust(mzClustSEXP);
    Rcpp::traits::input_parameter< double >::type blankPresenceThreshold(blankPresenceThresholdSEXP);
    Rcpp::traits::input_parameter< double >::type globalPresenceThreshold(globalPresenceThresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_filter_features_ms2(nts_xptr, top, minIntensity, relMinIntensity, blankClean, mzClust, blankPresenceThreshold, globalPresenceThreshold));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_metfrag_screening
bool rcpp_nts_metfrag_screening(SEXP nts_xptr, std::string metfrag_path, std::string database_type, std::string database_path, Rcpp::CharacterVector analyses, double ppm, double sec, double ppmMS2, double mzrMS2, int top_n, bool filtered, std::string java_path, std::string run_dir, bool debug, Rcpp::List extra_params);
RcppExport SEXP _StreamFind_rcpp_nts_metfrag_screening(SEXP nts_xptrSEXP, SEXP metfrag_pathSEXP, SEXP database_typeSEXP, SEXP database_pathSEXP, SEXP analysesSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP ppmMS2SEXP, SEXP mzrMS2SEXP, SEXP top_nSEXP, SEXP filteredSEXP, SEXP java_pathSEXP, SEXP run_dirSEXP, SEXP debugSEXP, SEXP extra_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nts_xptr(nts_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type metfrag_path(metfrag_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type database_type(database_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type database_path(database_pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type ppmMS2(ppmMS2SEXP);
    Rcpp::traits::input_parameter< double >::type mzrMS2(mzrMS2SEXP);
    Rcpp::traits::input_parameter< int >::type top_n(top_nSEXP);
    Rcpp::traits::input_parameter< bool >::type filtered(filteredSEXP);
    Rcpp::traits::input_parameter< std::string >::type java_path(java_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type run_dir(run_dirSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type extra_params(extra_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_metfrag_screening(nts_xptr, metfrag_path, database_type, database_path, analyses, ppm, sec, ppmMS2, mzrMS2, top_n, filtered, java_path, run_dir, debug, extra_params));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nts_assign_transformation_products
Rcpp::List rcpp_nts_assign_transformation_products(Rcpp::List suspects, Rcpp::List transformation_products, std::string chromatographic_phase, double mzrMS2);
RcppExport SEXP _StreamFind_rcpp_nts_assign_transformation_products(SEXP suspectsSEXP, SEXP transformation_productsSEXP, SEXP chromatographic_phaseSEXP, SEXP mzrMS2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type suspects(suspectsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transformation_products(transformation_productsSEXP);
    Rcpp::traits::input_parameter< std::string >::type chromatographic_phase(chromatographic_phaseSEXP);
    Rcpp::traits::input_parameter< double >::type mzrMS2(mzrMS2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nts_assign_transformation_products(suspects, transformation_products, chromatographic_phase, mzrMS2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_new
SEXP rcpp_project_new(std::string db_path, std::string project_id);
RcppExport SEXP _StreamFind_rcpp_project_new(SEXP db_pathSEXP, SEXP project_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type db_path(db_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type project_id(project_idSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_new(db_path, project_id));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_get_domain
std::string rcpp_project_get_domain(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_domain(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_domain(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_copy
SEXP rcpp_project_copy(SEXP project_xptr, std::string db_path, std::string project_id);
RcppExport SEXP _StreamFind_rcpp_project_copy(SEXP project_xptrSEXP, SEXP db_pathSEXP, SEXP project_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type db_path(db_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type project_id(project_idSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_copy(project_xptr, db_path, project_id));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_validate
void rcpp_project_validate(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_validate(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_project_validate(project_xptr);
    return R_NilValue;
END_RCPP
}
// rcpp_project_get_metadata
std::string rcpp_project_get_metadata(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_metadata(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_metadata(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_set_metadata
void rcpp_project_set_metadata(SEXP project_xptr, std::string metadata_json);
RcppExport SEXP _StreamFind_rcpp_project_set_metadata(SEXP project_xptrSEXP, SEXP metadata_jsonSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type metadata_json(metadata_jsonSEXP);
    rcpp_project_set_metadata(project_xptr, metadata_json);
    return R_NilValue;
END_RCPP
}
// rcpp_project_get_workflow
std::string rcpp_project_get_workflow(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_workflow(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_workflow(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_set_workflow
void rcpp_project_set_workflow(SEXP project_xptr, std::string workflow_json);
RcppExport SEXP _StreamFind_rcpp_project_set_workflow(SEXP project_xptrSEXP, SEXP workflow_jsonSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type workflow_json(workflow_jsonSEXP);
    rcpp_project_set_workflow(project_xptr, workflow_json);
    return R_NilValue;
END_RCPP
}
// rcpp_project_list_tables
CharacterVector rcpp_project_list_tables(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_list_tables(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_list_tables(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_get_audit
DataFrame rcpp_project_get_audit(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_audit(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_audit(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_get_cache_size
double rcpp_project_get_cache_size(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_cache_size(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_cache_size(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_get_cache
DataFrame rcpp_project_get_cache(SEXP project_xptr);
RcppExport SEXP _StreamFind_rcpp_project_get_cache(SEXP project_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_get_cache(project_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_delete_cache
void rcpp_project_delete_cache(SEXP project_xptr, Nullable<std::string> name);
RcppExport SEXP _StreamFind_rcpp_project_delete_cache(SEXP project_xptrSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type name(nameSEXP);
    rcpp_project_delete_cache(project_xptr, name);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_new
SEXP rcpp_project_mass_spec_new(SEXP project_xptr, CharacterVector file_paths, CharacterVector replicates, CharacterVector blanks);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_new(SEXP project_xptrSEXP, SEXP file_pathsSEXP, SEXP replicatesSEXP, SEXP blanksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type file_paths(file_pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type replicates(replicatesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type blanks(blanksSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_new(project_xptr, file_paths, replicates, blanks));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_import_files
void rcpp_project_mass_spec_import_files(SEXP mass_spec_xptr, CharacterVector file_paths, CharacterVector replicates, CharacterVector blanks);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_import_files(SEXP mass_spec_xptrSEXP, SEXP file_pathsSEXP, SEXP replicatesSEXP, SEXP blanksSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type file_paths(file_pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type replicates(replicatesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type blanks(blanksSEXP);
    rcpp_project_mass_spec_import_files(mass_spec_xptr, file_paths, replicates, blanks);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_remove_analysis
void rcpp_project_mass_spec_remove_analysis(SEXP mass_spec_xptr, std::string analysis);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_remove_analysis(SEXP mass_spec_xptrSEXP, SEXP analysisSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type analysis(analysisSEXP);
    rcpp_project_mass_spec_remove_analysis(mass_spec_xptr, analysis);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_list_analyses
DataFrame rcpp_project_mass_spec_list_analyses(SEXP mass_spec_xptr);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_list_analyses(SEXP mass_spec_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_list_analyses(mass_spec_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_analysis_names
CharacterVector rcpp_project_mass_spec_get_analysis_names(SEXP mass_spec_xptr);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_analysis_names(SEXP mass_spec_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_analysis_names(mass_spec_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_replicate_names
CharacterVector rcpp_project_mass_spec_get_replicate_names(SEXP mass_spec_xptr);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_replicate_names(SEXP mass_spec_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_replicate_names(mass_spec_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_set_replicate_names
void rcpp_project_mass_spec_set_replicate_names(SEXP mass_spec_xptr, CharacterVector values);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_set_replicate_names(SEXP mass_spec_xptrSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    rcpp_project_mass_spec_set_replicate_names(mass_spec_xptr, values);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_get_blank_names
CharacterVector rcpp_project_mass_spec_get_blank_names(SEXP mass_spec_xptr);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_blank_names(SEXP mass_spec_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_blank_names(mass_spec_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_set_blank_names
void rcpp_project_mass_spec_set_blank_names(SEXP mass_spec_xptr, CharacterVector values);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_set_blank_names(SEXP mass_spec_xptrSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    rcpp_project_mass_spec_set_blank_names(mass_spec_xptr, values);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_get_concentrations
NumericVector rcpp_project_mass_spec_get_concentrations(SEXP mass_spec_xptr);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_concentrations(SEXP mass_spec_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_concentrations(mass_spec_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_set_concentrations
void rcpp_project_mass_spec_set_concentrations(SEXP mass_spec_xptr, NumericVector values);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_set_concentrations(SEXP mass_spec_xptrSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_project_mass_spec_set_concentrations(mass_spec_xptr, values);
    return R_NilValue;
END_RCPP
}
// rcpp_project_mass_spec_get_spectra_headers
DataFrame rcpp_project_mass_spec_get_spectra_headers(SEXP mass_spec_xptr, SEXP analyses);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_spectra_headers(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_spectra_headers(mass_spec_xptr, analyses));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_chromatograms_headers
DataFrame rcpp_project_mass_spec_get_chromatograms_headers(SEXP mass_spec_xptr, SEXP analyses);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_chromatograms_headers(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_chromatograms_headers(mass_spec_xptr, analyses));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_spectra_tic
DataFrame rcpp_project_mass_spec_get_spectra_tic(SEXP mass_spec_xptr, SEXP analyses, std::vector<int> levels, NumericVector rt);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_spectra_tic(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP, SEXP levelsSEXP, SEXP rtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rt(rtSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_spectra_tic(mass_spec_xptr, analyses, levels, rt));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_raw_spectra
DataFrame rcpp_project_mass_spec_get_raw_spectra(SEXP mass_spec_xptr, SEXP analyses, std::vector<int> levels, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, CharacterVector id, double ppm, double sec, double millisec, bool all_traces, double isolation_window, float min_intensity_ms1, float min_intensity_ms2);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_raw_spectra(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP, SEXP levelsSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP idSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP, SEXP all_tracesSEXP, SEXP isolation_windowSEXP, SEXP min_intensity_ms1SEXP, SEXP min_intensity_ms2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    Rcpp::traits::input_parameter< bool >::type all_traces(all_tracesSEXP);
    Rcpp::traits::input_parameter< double >::type isolation_window(isolation_windowSEXP);
    Rcpp::traits::input_parameter< float >::type min_intensity_ms1(min_intensity_ms1SEXP);
    Rcpp::traits::input_parameter< float >::type min_intensity_ms2(min_intensity_ms2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_raw_spectra(mass_spec_xptr, analyses, levels, mass, mz, rt, mobility, id, ppm, sec, millisec, all_traces, isolation_window, min_intensity_ms1, min_intensity_ms2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_raw_spectra_eic
DataFrame rcpp_project_mass_spec_get_raw_spectra_eic(SEXP mass_spec_xptr, SEXP analyses, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, CharacterVector id, double ppm, double sec, double millisec);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_raw_spectra_eic(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP idSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_raw_spectra_eic(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_raw_spectra_ms1
DataFrame rcpp_project_mass_spec_get_raw_spectra_ms1(SEXP mass_spec_xptr, SEXP analyses, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, CharacterVector id, double ppm, double sec, double millisec, float mz_clust, float presence, float min_intensity);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms1(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP idSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP, SEXP mz_clustSEXP, SEXP presenceSEXP, SEXP min_intensitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    Rcpp::traits::input_parameter< float >::type mz_clust(mz_clustSEXP);
    Rcpp::traits::input_parameter< float >::type presence(presenceSEXP);
    Rcpp::traits::input_parameter< float >::type min_intensity(min_intensitySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_raw_spectra_ms1(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, mz_clust, presence, min_intensity));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_raw_spectra_ms2
DataFrame rcpp_project_mass_spec_get_raw_spectra_ms2(SEXP mass_spec_xptr, SEXP analyses, SEXP mass, SEXP mz, SEXP rt, SEXP mobility, CharacterVector id, double ppm, double sec, double millisec, float isolation_window, float mz_clust, float presence, float min_intensity);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms2(SEXP mass_spec_xptrSEXP, SEXP analysesSEXP, SEXP massSEXP, SEXP mzSEXP, SEXP rtSEXP, SEXP mobilitySEXP, SEXP idSEXP, SEXP ppmSEXP, SEXP secSEXP, SEXP millisecSEXP, SEXP isolation_windowSEXP, SEXP mz_clustSEXP, SEXP presenceSEXP, SEXP min_intensitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type analyses(analysesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mass(massSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mobility(mobilitySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< double >::type sec(secSEXP);
    Rcpp::traits::input_parameter< double >::type millisec(millisecSEXP);
    Rcpp::traits::input_parameter< float >::type isolation_window(isolation_windowSEXP);
    Rcpp::traits::input_parameter< float >::type mz_clust(mz_clustSEXP);
    Rcpp::traits::input_parameter< float >::type presence(presenceSEXP);
    Rcpp::traits::input_parameter< float >::type min_intensity(min_intensitySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_raw_spectra_ms2(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, isolation_window, mz_clust, presence, min_intensity));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_get_raw_chromatograms
DataFrame rcpp_project_mass_spec_get_raw_chromatograms(SEXP mass_spec_xptr, std::string analysis, std::vector<int> indices);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_get_raw_chromatograms(SEXP mass_spec_xptrSEXP, SEXP analysisSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mass_spec_xptr(mass_spec_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type analysis(analysisSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_get_raw_chromatograms(mass_spec_xptr, analysis, indices));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_spectra_new
SEXP rcpp_project_mass_spec_spectra_new(SEXP project_xptr, CharacterVector file_paths, CharacterVector replicates, CharacterVector blanks);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_spectra_new(SEXP project_xptrSEXP, SEXP file_pathsSEXP, SEXP replicatesSEXP, SEXP blanksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type file_paths(file_pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type replicates(replicatesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type blanks(blanksSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_spectra_new(project_xptr, file_paths, replicates, blanks));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_project_mass_spec_chromatograms_new
SEXP rcpp_project_mass_spec_chromatograms_new(SEXP project_xptr, CharacterVector file_paths, CharacterVector replicates, CharacterVector blanks);
RcppExport SEXP _StreamFind_rcpp_project_mass_spec_chromatograms_new(SEXP project_xptrSEXP, SEXP file_pathsSEXP, SEXP replicatesSEXP, SEXP blanksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type project_xptr(project_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type file_paths(file_pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type replicates(replicatesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type blanks(blanksSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_project_mass_spec_chromatograms_new(project_xptr, file_paths, replicates, blanks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StreamFind_rcpp_json_read_file", (DL_FUNC) &_StreamFind_rcpp_json_read_file, 1},
    {"_StreamFind_rcpp_json_read_subtree", (DL_FUNC) &_StreamFind_rcpp_json_read_subtree, 2},
    {"_StreamFind_rcpp_json_list_children", (DL_FUNC) &_StreamFind_rcpp_json_list_children, 2},
    {"_StreamFind_rcpp_asm_read_file", (DL_FUNC) &_StreamFind_rcpp_asm_read_file, 1},
    {"_StreamFind_rcpp_asm_index_table", (DL_FUNC) &_StreamFind_rcpp_asm_index_table, 1},
    {"_StreamFind_rcpp_asm_read_subtree", (DL_FUNC) &_StreamFind_rcpp_asm_read_subtree, 2},
    {"_StreamFind_rcpp_asm_read_primary_data", (DL_FUNC) &_StreamFind_rcpp_asm_read_primary_data, 1},
    {"_StreamFind_rcpp_asm_list_children", (DL_FUNC) &_StreamFind_rcpp_asm_list_children, 2},
    {"_StreamFind_rcpp_asm_validate_file", (DL_FUNC) &_StreamFind_rcpp_asm_validate_file, 3},
    {"_StreamFind_duckdb_list_tables", (DL_FUNC) &_StreamFind_duckdb_list_tables, 1},
    {"_StreamFind_duckdb_json_extension_info", (DL_FUNC) &_StreamFind_duckdb_json_extension_info, 1},
    {"_StreamFind_rcpp_json_schema_validation_ok", (DL_FUNC) &_StreamFind_rcpp_json_schema_validation_ok, 0},
    {"_StreamFind_rcpp_json_schema_validation_error", (DL_FUNC) &_StreamFind_rcpp_json_schema_validation_error, 0},
    {"_StreamFind_rcpp_json_make_example", (DL_FUNC) &_StreamFind_rcpp_json_make_example, 0},
    {"_StreamFind_rcpp_json_parse", (DL_FUNC) &_StreamFind_rcpp_json_parse, 1},
    {"_StreamFind_rcpp_project_non_target_analysis_new", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_new, 1},
    {"_StreamFind_rcpp_project_non_target_analysis_get_features", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_get_features, 13},
    {"_StreamFind_rcpp_project_non_target_analysis_get_features_count", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_get_features_count, 3},
    {"_StreamFind_rcpp_project_non_target_analysis_get_suspects", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_get_suspects, 11},
    {"_StreamFind_rcpp_project_non_target_analysis_get_internal_standards", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_get_internal_standards, 11},
    {"_StreamFind_rcpp_project_non_target_analysis_get_transformation_products", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_get_transformation_products, 1},
    {"_StreamFind_rcpp_project_non_target_analysis_assign_transformation_products", (DL_FUNC) &_StreamFind_rcpp_project_non_target_analysis_assign_transformation_products, 4},
    {"_StreamFind_rcpp_nts_find_features", (DL_FUNC) &_StreamFind_rcpp_nts_find_features, 13},
    {"_StreamFind_rcpp_nts_load_features_ms1", (DL_FUNC) &_StreamFind_rcpp_nts_load_features_ms1, 7},
    {"_StreamFind_rcpp_nts_load_features_ms2", (DL_FUNC) &_StreamFind_rcpp_nts_load_features_ms2, 6},
    {"_StreamFind_rcpp_nts_create_components", (DL_FUNC) &_StreamFind_rcpp_nts_create_components, 5},
    {"_StreamFind_rcpp_nts_annotate_components", (DL_FUNC) &_StreamFind_rcpp_nts_annotate_components, 7},
    {"_StreamFind_rcpp_nts_group_features", (DL_FUNC) &_StreamFind_rcpp_nts_group_features, 8},
    {"_StreamFind_rcpp_nts_fill_features", (DL_FUNC) &_StreamFind_rcpp_nts_fill_features, 13},
    {"_StreamFind_rcpp_nts_blank_subtraction", (DL_FUNC) &_StreamFind_rcpp_nts_blank_subtraction, 4},
    {"_StreamFind_rcpp_nts_filter_features", (DL_FUNC) &_StreamFind_rcpp_nts_filter_features, 32},
    {"_StreamFind_rcpp_nts_filter_suspects", (DL_FUNC) &_StreamFind_rcpp_nts_filter_suspects, 8},
    {"_StreamFind_rcpp_nts_filter_internal_standards", (DL_FUNC) &_StreamFind_rcpp_nts_filter_internal_standards, 8},
    {"_StreamFind_rcpp_nts_suspect_screening", (DL_FUNC) &_StreamFind_rcpp_nts_suspect_screening, 10},
    {"_StreamFind_rcpp_nts_filter_features_ms2", (DL_FUNC) &_StreamFind_rcpp_nts_filter_features_ms2, 8},
    {"_StreamFind_rcpp_nts_metfrag_screening", (DL_FUNC) &_StreamFind_rcpp_nts_metfrag_screening, 15},
    {"_StreamFind_rcpp_nts_assign_transformation_products", (DL_FUNC) &_StreamFind_rcpp_nts_assign_transformation_products, 4},
    {"_StreamFind_rcpp_project_new", (DL_FUNC) &_StreamFind_rcpp_project_new, 2},
    {"_StreamFind_rcpp_project_get_domain", (DL_FUNC) &_StreamFind_rcpp_project_get_domain, 1},
    {"_StreamFind_rcpp_project_copy", (DL_FUNC) &_StreamFind_rcpp_project_copy, 3},
    {"_StreamFind_rcpp_project_validate", (DL_FUNC) &_StreamFind_rcpp_project_validate, 1},
    {"_StreamFind_rcpp_project_get_metadata", (DL_FUNC) &_StreamFind_rcpp_project_get_metadata, 1},
    {"_StreamFind_rcpp_project_set_metadata", (DL_FUNC) &_StreamFind_rcpp_project_set_metadata, 2},
    {"_StreamFind_rcpp_project_get_workflow", (DL_FUNC) &_StreamFind_rcpp_project_get_workflow, 1},
    {"_StreamFind_rcpp_project_set_workflow", (DL_FUNC) &_StreamFind_rcpp_project_set_workflow, 2},
    {"_StreamFind_rcpp_project_list_tables", (DL_FUNC) &_StreamFind_rcpp_project_list_tables, 1},
    {"_StreamFind_rcpp_project_get_audit", (DL_FUNC) &_StreamFind_rcpp_project_get_audit, 1},
    {"_StreamFind_rcpp_project_get_cache_size", (DL_FUNC) &_StreamFind_rcpp_project_get_cache_size, 1},
    {"_StreamFind_rcpp_project_get_cache", (DL_FUNC) &_StreamFind_rcpp_project_get_cache, 1},
    {"_StreamFind_rcpp_project_delete_cache", (DL_FUNC) &_StreamFind_rcpp_project_delete_cache, 2},
    {"_StreamFind_rcpp_project_mass_spec_new", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_new, 4},
    {"_StreamFind_rcpp_project_mass_spec_import_files", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_import_files, 4},
    {"_StreamFind_rcpp_project_mass_spec_remove_analysis", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_remove_analysis, 2},
    {"_StreamFind_rcpp_project_mass_spec_list_analyses", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_list_analyses, 1},
    {"_StreamFind_rcpp_project_mass_spec_get_analysis_names", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_analysis_names, 1},
    {"_StreamFind_rcpp_project_mass_spec_get_replicate_names", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_replicate_names, 1},
    {"_StreamFind_rcpp_project_mass_spec_set_replicate_names", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_set_replicate_names, 2},
    {"_StreamFind_rcpp_project_mass_spec_get_blank_names", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_blank_names, 1},
    {"_StreamFind_rcpp_project_mass_spec_set_blank_names", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_set_blank_names, 2},
    {"_StreamFind_rcpp_project_mass_spec_get_concentrations", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_concentrations, 1},
    {"_StreamFind_rcpp_project_mass_spec_set_concentrations", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_set_concentrations, 2},
    {"_StreamFind_rcpp_project_mass_spec_get_spectra_headers", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_spectra_headers, 2},
    {"_StreamFind_rcpp_project_mass_spec_get_chromatograms_headers", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_chromatograms_headers, 2},
    {"_StreamFind_rcpp_project_mass_spec_get_spectra_tic", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_spectra_tic, 4},
    {"_StreamFind_rcpp_project_mass_spec_get_raw_spectra", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_raw_spectra, 15},
    {"_StreamFind_rcpp_project_mass_spec_get_raw_spectra_eic", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_raw_spectra_eic, 10},
    {"_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms1", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms1, 13},
    {"_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms2", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms2, 14},
    {"_StreamFind_rcpp_project_mass_spec_get_raw_chromatograms", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_get_raw_chromatograms, 3},
    {"_StreamFind_rcpp_project_mass_spec_spectra_new", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_spectra_new, 4},
    {"_StreamFind_rcpp_project_mass_spec_chromatograms_new", (DL_FUNC) &_StreamFind_rcpp_project_mass_spec_chromatograms_new, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_StreamFind(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
