# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_project_new <- function(db_path, project_id) {
    .Call(`_StreamFind_rcpp_project_new`, db_path, project_id)
}

rcpp_project_get_domain <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_domain`, project_xptr)
}

rcpp_project_copy <- function(project_xptr, db_path, project_id) {
    .Call(`_StreamFind_rcpp_project_copy`, project_xptr, db_path, project_id)
}

rcpp_project_validate <- function(project_xptr) {
    invisible(.Call(`_StreamFind_rcpp_project_validate`, project_xptr))
}

rcpp_project_close <- function(project_xptr) {
    invisible(.Call(`_StreamFind_rcpp_project_close`, project_xptr))
}

rcpp_project_get_metadata <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_metadata`, project_xptr)
}

rcpp_project_set_metadata <- function(project_xptr, metadata_json) {
    invisible(.Call(`_StreamFind_rcpp_project_set_metadata`, project_xptr, metadata_json))
}

rcpp_project_get_workflow <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_workflow`, project_xptr)
}

rcpp_project_set_workflow <- function(project_xptr, workflow_json) {
    invisible(.Call(`_StreamFind_rcpp_project_set_workflow`, project_xptr, workflow_json))
}

rcpp_project_list_tables <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_list_tables`, project_xptr)
}

rcpp_project_get_audit <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_audit`, project_xptr)
}

rcpp_project_get_cache_size <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_cache_size`, project_xptr)
}

rcpp_project_get_cache <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_cache`, project_xptr)
}

rcpp_project_delete_cache <- function(project_xptr, name = NULL) {
    invisible(.Call(`_StreamFind_rcpp_project_delete_cache`, project_xptr, name))
}

rcpp_decode_string <- function(base64_encoded) {
    .Call(`_StreamFind_rcpp_decode_string`, base64_encoded)
}

rcpp_project_mass_spec_new <- function(project_xptr, file_paths, replicates, blanks) {
    .Call(`_StreamFind_rcpp_project_mass_spec_new`, project_xptr, file_paths, replicates, blanks)
}

rcpp_project_mass_spec_import_files <- function(mass_spec_xptr, file_paths, replicates, blanks) {
    invisible(.Call(`_StreamFind_rcpp_project_mass_spec_import_files`, mass_spec_xptr, file_paths, replicates, blanks))
}

rcpp_project_mass_spec_remove_analysis <- function(mass_spec_xptr, analysis) {
    invisible(.Call(`_StreamFind_rcpp_project_mass_spec_remove_analysis`, mass_spec_xptr, analysis))
}

rcpp_project_mass_spec_list_analyses <- function(mass_spec_xptr) {
    .Call(`_StreamFind_rcpp_project_mass_spec_list_analyses`, mass_spec_xptr)
}

rcpp_project_mass_spec_get_analysis_names <- function(mass_spec_xptr) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_analysis_names`, mass_spec_xptr)
}

rcpp_project_mass_spec_get_replicate_names <- function(mass_spec_xptr) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_replicate_names`, mass_spec_xptr)
}

rcpp_project_mass_spec_set_replicate_names <- function(mass_spec_xptr, values) {
    invisible(.Call(`_StreamFind_rcpp_project_mass_spec_set_replicate_names`, mass_spec_xptr, values))
}

rcpp_project_mass_spec_get_blank_names <- function(mass_spec_xptr) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_blank_names`, mass_spec_xptr)
}

rcpp_project_mass_spec_set_blank_names <- function(mass_spec_xptr, values) {
    invisible(.Call(`_StreamFind_rcpp_project_mass_spec_set_blank_names`, mass_spec_xptr, values))
}

rcpp_project_mass_spec_get_concentrations <- function(mass_spec_xptr) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_concentrations`, mass_spec_xptr)
}

rcpp_project_mass_spec_set_concentrations <- function(mass_spec_xptr, values) {
    invisible(.Call(`_StreamFind_rcpp_project_mass_spec_set_concentrations`, mass_spec_xptr, values))
}

rcpp_project_mass_spec_get_spectra_headers <- function(mass_spec_xptr, analyses) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_spectra_headers`, mass_spec_xptr, analyses)
}

rcpp_project_mass_spec_get_chromatograms_headers <- function(mass_spec_xptr, analyses) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_chromatograms_headers`, mass_spec_xptr, analyses)
}

rcpp_project_mass_spec_get_spectra_tic <- function(mass_spec_xptr, analyses, levels, rtmin, rtmax) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_spectra_tic`, mass_spec_xptr, analyses, levels, rtmin, rtmax)
}

rcpp_project_mass_spec_get_raw_spectra <- function(mass_spec_xptr, analyses, levels, mass, mz, rt, mobility, id, ppm, sec, millisec, all_traces, isolation_window, min_intensity_ms1, min_intensity_ms2) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_raw_spectra`, mass_spec_xptr, analyses, levels, mass, mz, rt, mobility, id, ppm, sec, millisec, all_traces, isolation_window, min_intensity_ms1, min_intensity_ms2)
}

rcpp_project_mass_spec_get_raw_spectra_eic <- function(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_raw_spectra_eic`, mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec)
}

rcpp_project_mass_spec_get_raw_spectra_ms1 <- function(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, mz_clust, presence, min_intensity) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms1`, mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, mz_clust, presence, min_intensity)
}

rcpp_project_mass_spec_get_raw_spectra_ms2 <- function(mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, isolation_window, mz_clust, presence, min_intensity) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_raw_spectra_ms2`, mass_spec_xptr, analyses, mass, mz, rt, mobility, id, ppm, sec, millisec, isolation_window, mz_clust, presence, min_intensity)
}

rcpp_project_mass_spec_get_raw_chromatograms <- function(mass_spec_xptr, analysis, indices) {
    .Call(`_StreamFind_rcpp_project_mass_spec_get_raw_chromatograms`, mass_spec_xptr, analysis, indices)
}

rcpp_project_mass_spec_spectra_new <- function(project_xptr, file_paths, replicates, blanks) {
    .Call(`_StreamFind_rcpp_project_mass_spec_spectra_new`, project_xptr, file_paths, replicates, blanks)
}

rcpp_project_mass_spec_chromatograms_new <- function(project_xptr, file_paths, replicates, blanks) {
    .Call(`_StreamFind_rcpp_project_mass_spec_chromatograms_new`, project_xptr, file_paths, replicates, blanks)
}

rcpp_project_non_target_analysis_new <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_new`, project_xptr)
}

rcpp_project_non_target_analysis_get_features <- function(nta_xptr, analyses, features, groups, components, mass, mz, rt, mobility, ppm, sec, millisec, include_filtered) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_get_features`, nta_xptr, analyses, features, groups, components, mass, mz, rt, mobility, ppm, sec, millisec, include_filtered)
}

rcpp_project_non_target_analysis_get_features_count <- function(nta_xptr, analyses, include_filtered) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_get_features_count`, nta_xptr, analyses, include_filtered)
}

rcpp_project_nta_get_matrix_suppression <- function(nta_xptr, analyses = as.character( c("")), rtWindowVal = 10.0, refBlankReplicate = NULL) {
    .Call(`_StreamFind_rcpp_project_nta_get_matrix_suppression`, nta_xptr, analyses, rtWindowVal, refBlankReplicate)
}

rcpp_project_nta_correct_matrix_suppression <- function(nta_xptr, mpRtWindow = 10.0, refBlankReplicate = NULL) {
    .Call(`_StreamFind_rcpp_project_nta_correct_matrix_suppression`, nta_xptr, mpRtWindow, refBlankReplicate)
}

rcpp_project_non_target_analysis_get_suspects <- function(nta_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_get_suspects`, nta_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec)
}

rcpp_project_non_target_analysis_get_internal_standards <- function(nta_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_get_internal_standards`, nta_xptr, analyses, features, groups, mass, mz, rt, mobility, ppm, sec, millisec)
}

rcpp_project_non_target_analysis_get_transformation_products <- function(nta_xptr) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_get_transformation_products`, nta_xptr)
}

rcpp_project_non_target_analysis_assign_transformation_products <- function(nta_xptr, transformation_products, chromatographic_phase = "reverse_phase", mzrMS2 = 0.008) {
    .Call(`_StreamFind_rcpp_project_non_target_analysis_assign_transformation_products`, nta_xptr, transformation_products, chromatographic_phase, mzrMS2)
}

rcpp_project_nta_find_features <- function(nta_xptr, rtWindowsMin, rtWindowsMax, ppmThreshold = 15.0, noiseThreshold = 15.0, minSNR = 3.0, minTraces = 3L, baselineWindow = 200.0, maxWidth = 100.0, baseQuantile = 0.10, debugAnalysis = "", debugMZ = 0.0, debugSpecIdx = -1L) {
    .Call(`_StreamFind_rcpp_project_nta_find_features`, nta_xptr, rtWindowsMin, rtWindowsMax, ppmThreshold, noiseThreshold, minSNR, minTraces, baselineWindow, maxWidth, baseQuantile, debugAnalysis, debugMZ, debugSpecIdx)
}

rcpp_project_nta_load_features_ms1 <- function(nta_xptr, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence) {
    .Call(`_StreamFind_rcpp_project_nta_load_features_ms1`, nta_xptr, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence)
}

rcpp_project_nta_load_features_ms2 <- function(nta_xptr, filtered, minTracesIntensity, isolationWindow, mzClust, presence) {
    .Call(`_StreamFind_rcpp_project_nta_load_features_ms2`, nta_xptr, filtered, minTracesIntensity, isolationWindow, mzClust, presence)
}

rcpp_project_nta_create_components <- function(nta_xptr, rtWindow, minCorrelation = 0.8, debugRT = 0.0, debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_project_nta_create_components`, nta_xptr, rtWindow, minCorrelation, debugRT, debugAnalysis)
}

rcpp_project_nta_annotate_components <- function(nta_xptr, maxIsotopes = 5L, maxCharge = 1L, maxGaps = 1L, ppm = 10.0, isotopeElements = as.character( c("C:1-60", "N:0-10", "O:0-20", "S:0-4", "Cl:0-6", "Br:0-4")), debugComponent = "", debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_project_nta_annotate_components`, nta_xptr, maxIsotopes, maxCharge, maxGaps, ppm, isotopeElements, debugComponent, debugAnalysis)
}

rcpp_project_nta_group_features <- function(nta_xptr, method = "obi_warp", rtDeviation = 5.0, ppm = 5.0, minSamples = 1L, binSize = 5.0, debug = FALSE, debugRT = 0.0) {
    .Call(`_StreamFind_rcpp_project_nta_group_features`, nta_xptr, method, rtDeviation, ppm, minSamples, binSize, debug, debugRT)
}

rcpp_project_nta_fill_features <- function(nta_xptr, withinReplicate = FALSE, filtered = FALSE, rtExpand = 10.0, mzExpand = 0.01, maxPeakWidth = 30.0, minTracesIntensity = 1000.0, minNumberTraces = 5L, minIntensity = 5000.0, rtApexDeviation = 5.0, minSignalToNoiseRatio = 3.0, minGaussianFit = 0.2, debugFG = "") {
    .Call(`_StreamFind_rcpp_project_nta_fill_features`, nta_xptr, withinReplicate, filtered, rtExpand, mzExpand, maxPeakWidth, minTracesIntensity, minNumberTraces, minIntensity, rtApexDeviation, minSignalToNoiseRatio, minGaussianFit, debugFG)
}

rcpp_project_nta_blank_subtraction <- function(nta_xptr, blankThreshold = 5.0, rtExpand = 10.0, mzExpand = 0.005) {
    .Call(`_StreamFind_rcpp_project_nta_blank_subtraction`, nta_xptr, blankThreshold, rtExpand, mzExpand)
}

rcpp_project_nta_filter_features <- function(nta_xptr, minSN = NA_real_, minIntensity = NA_real_, minArea = NA_real_, minWidth = NA_real_, maxWidth = NA_real_, maxPPM = NA_real_, minFwhmRT = NA_real_, maxFwhmRT = NA_real_, minFwhmMZ = NA_real_, maxFwhmMZ = NA_real_, minGaussianA = NA_real_, minGaussianMu = NA_real_, maxGaussianMu = NA_real_, minGaussianSigma = NA_real_, maxGaussianSigma = NA_real_, minGaussianR2 = NA_real_, maxJaggedness = NA_real_, minSharpness = NA_real_, minAsymmetry = NA_real_, maxAsymmetry = NA_real_, maxModality = NA_integer_, minPlates = NA_real_, onlyFilled = as.logical( c(NA_LOGICAL)), removeFilled = FALSE, minSizeEIC = NA_integer_, minSizeMS1 = NA_integer_, minSizeMS2 = NA_integer_, minRelPresenceReplicate = NA_real_, removeIsotopes = FALSE, removeAdducts = FALSE, removeLosses = FALSE) {
    .Call(`_StreamFind_rcpp_project_nta_filter_features`, nta_xptr, minSN, minIntensity, minArea, minWidth, maxWidth, maxPPM, minFwhmRT, maxFwhmRT, minFwhmMZ, maxFwhmMZ, minGaussianA, minGaussianMu, maxGaussianMu, minGaussianSigma, maxGaussianSigma, minGaussianR2, maxJaggedness, minSharpness, minAsymmetry, maxAsymmetry, maxModality, minPlates, onlyFilled, removeFilled, minSizeEIC, minSizeMS1, minSizeMS2, minRelPresenceReplicate, removeIsotopes, removeAdducts, removeLosses)
}

rcpp_project_nta_filter_suspects <- function(nta_xptr, names = as.character( c()), minScore = NA_real_, maxErrorRT = NA_real_, maxErrorMass = NA_real_, idLevels = as.integer( c()), minSharedFragments = 0L, minCosineSimilarity = NA_real_) {
    .Call(`_StreamFind_rcpp_project_nta_filter_suspects`, nta_xptr, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity)
}

rcpp_project_nta_filter_internal_standards <- function(nta_xptr, names = as.character( c()), minScore = NA_real_, maxErrorRT = NA_real_, maxErrorMass = NA_real_, idLevels = as.integer( c()), minSharedFragments = 0L, minCosineSimilarity = NA_real_) {
    .Call(`_StreamFind_rcpp_project_nta_filter_internal_standards`, nta_xptr, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity)
}

rcpp_project_nta_find_internal_standards <- function(nta_xptr, suspects, analyses = as.character( c("")), ppm = 5.0, sec = 10.0, ppmMS2 = 10.0, mzrMS2 = 0.008, minCosineSimilarity = 0.7, minSharedFragments = 3L, filtered = TRUE) {
    .Call(`_StreamFind_rcpp_project_nta_find_internal_standards`, nta_xptr, suspects, analyses, ppm, sec, ppmMS2, mzrMS2, minCosineSimilarity, minSharedFragments, filtered)
}

rcpp_project_nta_suspect_screening <- function(nta_xptr, suspects, analyses = as.character( c("")), ppm = 5.0, sec = 10.0, ppmMS2 = 10.0, mzrMS2 = 0.008, minCosineSimilarity = 0.7, minSharedFragments = 3L, filtered = FALSE) {
    .Call(`_StreamFind_rcpp_project_nta_suspect_screening`, nta_xptr, suspects, analyses, ppm, sec, ppmMS2, mzrMS2, minCosineSimilarity, minSharedFragments, filtered)
}

rcpp_project_nta_filter_features_ms2 <- function(nta_xptr, top = 0L, minIntensity = NA_real_, relMinIntensity = NA_real_, blankClean = FALSE, mzClust = 0.005, blankPresenceThreshold = 0.8, globalPresenceThreshold = 0.1) {
    .Call(`_StreamFind_rcpp_project_nta_filter_features_ms2`, nta_xptr, top, minIntensity, relMinIntensity, blankClean, mzClust, blankPresenceThreshold, globalPresenceThreshold)
}

rcpp_project_nta_metfrag_screening <- function(nta_xptr, metfrag_path, database_type = "PubChem", database_path = "", analyses = as.character( c("")), ppm = 5.0, sec = 10.0, ppmMS2 = 10.0, mzrMS2 = 0.008, top_n = 1L, score_types = as.character( c("FragmenterScore")), score_weights = as.numeric( c(1.0)), pre_processing_candidate_filter = as.character( c("UnconnectedCompoundFilter", "IsotopeFilter")), post_processing_candidate_filter = as.character( c("InChIKeyFilter")), maximum_tree_depth = 2L, number_threads = 1L, use_smiles = TRUE, filtered = FALSE, java_path = "java", run_dir = "", debug = FALSE, extra_params = NULL) {
    .Call(`_StreamFind_rcpp_project_nta_metfrag_screening`, nta_xptr, metfrag_path, database_type, database_path, analyses, ppm, sec, ppmMS2, mzrMS2, top_n, score_types, score_weights, pre_processing_candidate_filter, post_processing_candidate_filter, maximum_tree_depth, number_threads, use_smiles, filtered, java_path, run_dir, debug, extra_params)
}

rcpp_project_nta_assign_transformation_products <- function(suspects, transformation_products, chromatographic_phase = "reverse_phase", mzrMS2 = 0.008) {
    .Call(`_StreamFind_rcpp_project_nta_assign_transformation_products`, suspects, transformation_products, chromatographic_phase, mzrMS2)
}

rcpp_json_make_example <- function() {
    .Call(`_StreamFind_rcpp_json_make_example`)
}

rcpp_json_parse <- function(s) {
    .Call(`_StreamFind_rcpp_json_parse`, s)
}

rcpp_json_read_file <- function(file_path) {
    .Call(`_StreamFind_rcpp_json_read_file`, file_path)
}

rcpp_json_read_subtree <- function(file_path, path) {
    .Call(`_StreamFind_rcpp_json_read_subtree`, file_path, path)
}

rcpp_json_list_children <- function(file_path, path = "") {
    .Call(`_StreamFind_rcpp_json_list_children`, file_path, path)
}

rcpp_json_schema_validation_ok <- function() {
    .Call(`_StreamFind_rcpp_json_schema_validation_ok`)
}

rcpp_json_schema_validation_error <- function() {
    .Call(`_StreamFind_rcpp_json_schema_validation_error`)
}

rcpp_asm_read_file <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_read_file`, file_path)
}

rcpp_asm_index_table <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_index_table`, file_path)
}

rcpp_asm_read_subtree <- function(file_path, path) {
    .Call(`_StreamFind_rcpp_asm_read_subtree`, file_path, path)
}

rcpp_asm_read_primary_data <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_read_primary_data`, file_path)
}

rcpp_asm_list_children <- function(file_path, path = "") {
    .Call(`_StreamFind_rcpp_asm_list_children`, file_path, path)
}

rcpp_asm_validate_file <- function(json_file_path, schema_file, schema_root_dir = "") {
    .Call(`_StreamFind_rcpp_asm_validate_file`, json_file_path, schema_file, schema_root_dir)
}

duckdb_list_tables <- function(db_path) {
    .Call(`_StreamFind_duckdb_list_tables`, db_path)
}

duckdb_json_extension_info <- function(db_path) {
    .Call(`_StreamFind_duckdb_json_extension_info`, db_path)
}

#' Render a structure as SVG with the native Open Babel backend
#'
#' Converts a `SMILES` or `InChI` structure into an SVG depiction using the
#' embedded Open Babel runtime. The returned SVG has a transparent background.
#'
#' @param SMILES Optional structure in SMILES format.
#' @param InChI Optional structure in InChI format.
#' @param width Width in pixels.
#' @param height Height in pixels.
#' @param darkMode Logical, use a light bond color suitable for dark backgrounds.
#' @return A length-one character string containing SVG markup, or `""` on failure.
#' @export
rcpp_openbabel_structure_svg <- function(SMILES = NULL, InChI = NULL, width = 140L, height = 120L, darkMode = FALSE) {
    .Call(`_StreamFind_rcpp_openbabel_structure_svg`, SMILES, InChI, width, height, darkMode)
}

#' Create a suspect screening table with the native Open Babel backend
#'
#' Normalizes suspect structures with the embedded Open Babel runtime and
#' returns the standard suspect-screening columns. When `file` is provided, the
#' resulting table is also written as CSV using `data.table::fwrite()`.
#'
#' @param suspects A `data.frame` with required column `name` and at least one
#'   structure column from `SMILES` or `InChI`. Optional columns `rt`,
#'   `ms2_positive`, and `ms2_negative` are preserved.
#' @param file Optional output CSV path. When provided, the normalized table is
#'   written to disk.
#' @return A `data.frame` with columns `name`, `formula`, `mass`, `rt`,
#'   `SMILES`, `InChI`, `InChIKey`, `xLogP`, `ms2_positive`, and
#'   `ms2_negative`.
#' @export
rcpp_get_suspects_screening_csv <- function(suspects, file = NULL) {
    .Call(`_StreamFind_rcpp_get_suspects_screening_csv`, suspects, file)
}

